name: Deploy to Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop existing containers
        run: docker compose down || true

      - name: Remove old images
        run: |
          docker rmi galgo-server:latest || true
          docker rmi galgo-client:latest || true

      - name: Build and start services
        run: docker compose up -d --build

      - name: Show running containers
        run: docker ps

      - name: Show logs
        run: docker compose logs --tail=50